general:
  enable_cache: true
  dir_cache: /tmp/mlpipe/tmp
reporting:
  hosting_url_prefix: "https://cdn.jsdelivr.net/gh/robie2011/mlpipe-SensorReportViewer@master/cdn/"
  base_href: "#"
  html_template_path: "./templates/index.html"

training:
  dir_data: /tmp/mlpipe/training
  model_checkpoint_monitor: 'val_loss'
