name: empa_mlp_regression_abluft
source:
  name: mlpipe.dsl.sources.EmpaCsvSourceAdapter
  pathToFile: data/meeting_room_sensors_201807_201907.csv
  fields:
    - 3200000 as TempAussen
    - 40210012 as TempInnen
    - 40210002 as Zuluft
    - 40210005 as Abluft
    - 40210013 as CO2
    - 40210148 as Präsenz

pipelinePrimary:
  - name: mlpipe.dsl.processors.NanRemover

pipelineSecondary:
  - name: mlpipe.dsl.processors.Scaler
    scaler: sklearn.preprocessing.MinMaxScaler
    fields:
      - TempAussen
      - Zuluft
      - Abluft
      - CO2
  - name: mlpipe.dsl.processors.SeedSetup
    numpy: 2
    tensorflow: 2


model:
  input:
    - TempAussen
    - Zuluft
    - Abluft
    - CO2
    - Präsenz

  target: TempInnen
  predictionType: regression
  testRatio: .20

  sequentialModel:
    - name: keras.layers.Dense
      units: 200
      activation: relu
    - name: keras.layers.Dense
      units: 100
      activation: tanh
    - name: keras.layers.Dense
      units: 50
      activation: relu
    - name: keras.layers.Dense
      units: 1
      activation: linear

  compile:
    loss: mean_absolute_error
    optimizer: rmsprop
    metrics:
      - mean_absolute_percentage_error
      - mae

  fit:
    epochs: 50
    batch_size: 4320
