const fs = require("fs")
const aggregators = JSON.parse(fs.readFileSync("aggregators.schema.json").toString())

const propertiesToDelete = ["_condition", "sequence", "generate"]

aggregators.definitions.aggregators.oneOf.forEach(
    a => propertiesToDelete.forEach(name => delete a["properties"][name]))

aggregators.definitions.aggregators.oneOf.forEach(
    a => a.required = a.required.filter(name => propertiesToDelete.indexOf(name) === -1)
)

const metrics = aggregators.definitions.aggregators

aggregators.definitions = { metrics: metrics }
aggregators.title = "Metrics"
aggregators.description = "generated by generate_metrics_schema.js"

fs.writeFileSync("metrics.schema.json", JSON.stringify(aggregators, null, 4))