name: mlp_simple
source:
  name: mlpipe.dsl.sources.EmpaCsvSourceAdapter
  pathToFile: data/meeting_room_sensors_201807_201907.csv
  fields:
    - 3200000 as TempAussen
    - 40210012 as TempInnen
    - 40210002 as Zuluft
    - 40210005 as Abluft
    - 40210013 as CO2
    - 40210148 as Präsenz

pipelinePrimary:
  - name: mlpipe.dsl.processors.SeedSetup
    numpy: 1
    tensorflow: 1
  - name: mlpipe.dsl.processors.Resampler
    freq: 1T
  - name: mlpipe.dsl.processors.Interpolation
    method: linear
    max_consecutive_interpolated_value: 15
  - name: mlpipe.dsl.processors.TimeExtractor
    extract: hour
    outputField: Stunden
  - name: mlpipe.dsl.processors.TimeExtractor
    extract: weekday
    outputField: Wochentag
  - name: mlpipe.dsl.aggregators.Mean
    sequence: 15
    generate:
      - inputField: CO2
        outputField: CO2_Mean
      - inputField: TempInnen
        outputField: TempInnen_Mean
      - inputField: Zuluft
        outputField: Zuluft_Mean
  - name: mlpipe.dsl.aggregators.Trend
    sequence: 15
    generate:
      - inputField: CO2
        outputField: CO2_Trend
      - inputField: TempInnen
        outputField: TempInnen_Trend
      - inputField: Zuluft
        outputField: Zuluft_Trend

pipelineSecondary:
  - name: mlpipe.dsl.processors.Scaler
    scaler: sklearn.preprocessing.RobustScaler
    fields:
      - TempAussen
      - TempInnen
      - Zuluft
      - Abluft
      - CO2
      - CO2_Mean
      - TempInnen_Mean
      - Zuluft_Mean
      - CO2_Trend
      - TempInnen_Trend
      - Zuluft_Trend
  - name: mlpipe.dsl.processors.RangeEncoder
    value_from: 0
    value_to: 24
    generate:
      - inputField: Stunden
        outputField: StundenOneHot
  - name: mlpipe.dsl.processors.RangeEncoder
    value_from: 0
    value_to: 7
    generate:
      - inputField: Wochentag
        outputField: WochentagOneHot
  - name: mlpipe.dsl.processors.NanRemover
  - name: mlpipe.dsl.processors.Shuffle

model:
  input:
    - TempAussen
    - TempInnen
    - Zuluft
    - Abluft
    - CO2
    - CO2_Mean
    - TempInnen_Mean
    - Zuluft_Mean
    - CO2_Trend
    - TempInnen_Trend
    - Zuluft_Trend
    - REGEX:StundenOneHot\$.*
    - REGEX:WochentagOneHot\$.*
  target: Präsenz
  testRatio: .1
  sequentialModel:
    - name: keras.layers.Dense
      units: 200
      activation: relu
    - name: keras.layers.Dense
      units: 50
      activation: relu
    - name: keras.layers.Dense
      units: 1
      activation: sigmoid
  compile:
    optimizer: Adam
    loss: binary_crossentropy
    metrics:
      - accuracy
  fit:
    batch_size: 4000
    epochs: 50
    class_weight: auto

